image: docker:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - package

test:
  services:
    - mongo
  stage: test
  image: node:8.9.4-alpine
  before_script:
    - yarn install
    - yarn build
  script:
    - yarn test

build:
  stage: build
  image: node:8.9.4-alpine
  dependencies:
    - test
  script:
    - yarn run build
    - yarn cache clean
  after_script:
  artifacts:
    untracked: true

docker-build:
  stage: package
  image: docker:latest
  dependencies:
    - test
    - build
  services:
    - docker:dind
  before_script:
    - ls
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
  script:
    - docker build -t registry.gitlab.com/$CI_PROJECT_NAME .
    - docker tag registry.gitlab.com/$CI_PROJECT_NAME registry.gitlab.com/energybox/$CI_PROJECT_NAME:$CI_BUILD_REF
    - docker push registry.gitlab.com/$CI_PROJECT_NAME:$CI_BUILD_REF
    - docker push registry.gitlab.com/$CI_PROJECT_NAME:latest

